[package]
name = "br_eng"
version = "0.1.0"
edition = "2021"
default-run="br_eng"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
exer=[]
[dependencies]
image="0.24.2"
